name: 'Windows MSYS2'

env:
  CMAKE_VERSION: '3.16.x'
  CMAKE_BUILD_TYPE: 'Release'
  CMAKE_BUILD_PREFIX: './build'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟨', sys: mingw32, env: i686, name: MINGW32 }
          - { icon: '🟦', sys: mingw64, env: x86_64, name: MINGW64 }
          - { icon: '🟩', sys: ucrt64,  env: ucrt-x86_64, name: UCRT64 }  # Experimental!
          - { icon: '🟥', sys: clang64, env: clang-x86_64, name: Clang64 } # Experimental!
    name: '🚧 ${{ matrix.icon }} ${{ matrix.name }}'
    defaults:
      run:
        shell: msys2 {0}

    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2.3.5
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        path-type: minimal
        release: true
        update: true
        install: >-
          git
          make
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja
          pcre

    - name: '🔧 Configure'
      run: cmake -S . -B ${{ env.CMAKE_BUILD_PREFIX }} -D CMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

    - name: '⚙️ Build'
      run: cmake --build ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --parallel 2

    - name: '🧪 Run tests'
      working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
      run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j2 -VV --output-on-failure
